// 内置 boop emoji 清单 + 中文别名（共 65 项）。
// 与 plugins/official/media/index.js 的 categories 同源维护；VRChat 增减内置表情时两处同步改。
// emojiId 推导规则与 media 一致：default_${nameEn.replace(/ /g,'_').toLowerCase()}

export default [
  // ── 表情(20) ──
  { emojiId: 'default_angry', nameEn: 'Angry', category: '表情', aliasesZh: ['生气', '愤怒'] },
  { emojiId: 'default_blushing', nameEn: 'Blushing', category: '表情', aliasesZh: ['脸红', '害羞'] },
  { emojiId: 'default_crying', nameEn: 'Crying', category: '表情', aliasesZh: ['哭', '大哭'] },
  { emojiId: 'default_frown', nameEn: 'Frown', category: '表情', aliasesZh: ['皱眉', '不悦'] },
  { emojiId: 'default_hand_wave', nameEn: 'Hand Wave', category: '表情', aliasesZh: ['挥手', '招手', '打招呼'] },
  { emojiId: 'default_hang_ten', nameEn: 'Hang Ten', category: '表情', aliasesZh: ['冲浪'] },
  { emojiId: 'default_in_love', nameEn: 'In Love', category: '表情', aliasesZh: ['恋爱', '心动'] },
  { emojiId: 'default_jack_o_lantern', nameEn: 'Jack O Lantern', category: '表情', aliasesZh: ['南瓜灯'] },
  { emojiId: 'default_kiss', nameEn: 'Kiss', category: '表情', aliasesZh: ['亲亲', '么么'] },
  { emojiId: 'default_laugh', nameEn: 'Laugh', category: '表情', aliasesZh: ['大笑', '笑', '哈哈哈'] },
  { emojiId: 'default_skull', nameEn: 'Skull', category: '表情', aliasesZh: ['骷髅', '去世'] },
  { emojiId: 'default_smile', nameEn: 'Smile', category: '表情', aliasesZh: ['微笑', '嘿嘿'] },
  { emojiId: 'default_spooky_ghost', nameEn: 'Spooky Ghost', category: '表情', aliasesZh: ['幽灵', '鬼'] },
  { emojiId: 'default_stoic', nameEn: 'Stoic', category: '表情', aliasesZh: ['淡定', '面瘫'] },
  { emojiId: 'default_sunglasses', nameEn: 'Sunglasses', category: '表情', aliasesZh: ['墨镜', '装酷'] },
  { emojiId: 'default_thinking', nameEn: 'Thinking', category: '表情', aliasesZh: ['思考', '想'] },
  { emojiId: 'default_thumbs_down', nameEn: 'Thumbs Down', category: '表情', aliasesZh: ['踩', '鄙视'] },
  { emojiId: 'default_thumbs_up', nameEn: 'Thumbs Up', category: '表情', aliasesZh: ['竖大拇指', '点赞', '赞'] },
  { emojiId: 'default_tongue_out', nameEn: 'Tongue Out', category: '表情', aliasesZh: ['吐舌头', '调皮'] },
  { emojiId: 'default_wow', nameEn: 'Wow', category: '表情', aliasesZh: ['哇', '震惊'] },

  // ── 指令(8) ──
  { emojiId: 'default_arrow_point', nameEn: 'Arrow Point', category: '指令', aliasesZh: ['指', '箭头'] },
  { emojiId: "default_can't_see", nameEn: "Can't see", category: '指令', aliasesZh: ['看不到', '看不见'] },
  { emojiId: 'default_hourglass', nameEn: 'Hourglass', category: '指令', aliasesZh: ['沙漏', '等待'] },
  { emojiId: 'default_keyboard', nameEn: 'Keyboard', category: '指令', aliasesZh: ['键盘', '打字'] },
  { emojiId: 'default_no_headphones', nameEn: 'No Headphones', category: '指令', aliasesZh: ['没耳机'] },
  { emojiId: 'default_no_mic', nameEn: 'No Mic', category: '指令', aliasesZh: ['没麦', '静音'] },
  { emojiId: 'default_portal', nameEn: 'Portal', category: '指令', aliasesZh: ['传送门'] },
  { emojiId: 'default_shush', nameEn: 'Shush', category: '指令', aliasesZh: ['嘘', '安静'] },

  // ── 季节/装饰(28) ──
  { emojiId: 'default_bats', nameEn: 'Bats', category: '季节/装饰', aliasesZh: ['蝙蝠'] },
  { emojiId: 'default_cloud', nameEn: 'Cloud', category: '季节/装饰', aliasesZh: ['云', '云朵'] },
  { emojiId: 'default_fire', nameEn: 'Fire', category: '季节/装饰', aliasesZh: ['火', '燃起来了'] },
  { emojiId: 'default_snow_fall', nameEn: 'Snow Fall', category: '季节/装饰', aliasesZh: ['下雪'] },
  { emojiId: 'default_snowball', nameEn: 'Snowball', category: '季节/装饰', aliasesZh: ['雪球'] },
  { emojiId: 'default_splash', nameEn: 'Splash', category: '季节/装饰', aliasesZh: ['水花', '泼水'] },
  { emojiId: 'default_web', nameEn: 'Web', category: '季节/装饰', aliasesZh: ['蜘蛛网'] },
  { emojiId: 'default_beer', nameEn: 'Beer', category: '季节/装饰', aliasesZh: ['啤酒'] },
  { emojiId: 'default_candy', nameEn: 'Candy', category: '季节/装饰', aliasesZh: ['糖果'] },
  { emojiId: 'default_candy_cane', nameEn: 'Candy Cane', category: '季节/装饰', aliasesZh: ['拐杖糖'] },
  { emojiId: 'default_candy_corn', nameEn: 'Candy Corn', category: '季节/装饰', aliasesZh: ['玉米糖'] },
  { emojiId: 'default_champagne', nameEn: 'Champagne', category: '季节/装饰', aliasesZh: ['香槟'] },
  { emojiId: 'default_drink', nameEn: 'Drink', category: '季节/装饰', aliasesZh: ['喝', '饮料'] },
  { emojiId: 'default_gingerbread', nameEn: 'Gingerbread', category: '季节/装饰', aliasesZh: ['姜饼'] },
  { emojiId: 'default_ice_cream', nameEn: 'Ice Cream', category: '季节/装饰', aliasesZh: ['冰淇淋', '冰激凌'] },
  { emojiId: 'default_pineapple', nameEn: 'Pineapple', category: '季节/装饰', aliasesZh: ['菠萝'] },
  { emojiId: 'default_pizza', nameEn: 'Pizza', category: '季节/装饰', aliasesZh: ['披萨'] },
  { emojiId: 'default_tomato', nameEn: 'Tomato', category: '季节/装饰', aliasesZh: ['番茄', '西红柿'] },
  { emojiId: 'default_beachball', nameEn: 'Beachball', category: '季节/装饰', aliasesZh: ['沙滩球'] },
  { emojiId: 'default_coal', nameEn: 'Coal', category: '季节/装饰', aliasesZh: ['煤'] },
  { emojiId: 'default_confetti', nameEn: 'Confetti', category: '季节/装饰', aliasesZh: ['彩带', '彩纸'] },
  { emojiId: 'default_gift', nameEn: 'Gift', category: '季节/装饰', aliasesZh: ['礼物', '送礼'] },
  { emojiId: 'default_gifts', nameEn: 'Gifts', category: '季节/装饰', aliasesZh: ['礼物们'] },
  { emojiId: 'default_life_ring', nameEn: 'Life Ring', category: '季节/装饰', aliasesZh: ['救生圈'] },
  { emojiId: 'default_mistletoe', nameEn: 'Mistletoe', category: '季节/装饰', aliasesZh: ['槲寄生'] },
  { emojiId: 'default_money', nameEn: 'Money', category: '季节/装饰', aliasesZh: ['钱', '发财'] },
  { emojiId: 'default_neon_shades', nameEn: 'Neon Shades', category: '季节/装饰', aliasesZh: ['霓虹墨镜'] },
  { emojiId: 'default_sun_lotion', nameEn: 'Sun Lotion', category: '季节/装饰', aliasesZh: ['防晒霜'] },

  // ── 通用(9) ──
  { emojiId: 'default_boo', nameEn: 'Boo', category: '通用', aliasesZh: ['吓', '吓唬'] },
  { emojiId: 'default_broken_heart', nameEn: 'Broken Heart', category: '通用', aliasesZh: ['心碎', '伤心'] },
  { emojiId: 'default_exclamation', nameEn: 'Exclamation', category: '通用', aliasesZh: ['感叹号', '注意'] },
  { emojiId: 'default_go', nameEn: 'Go', category: '通用', aliasesZh: ['冲', '出发'] },
  { emojiId: 'default_heart', nameEn: 'Heart', category: '通用', aliasesZh: ['心', '爱心'] },
  { emojiId: 'default_music_note', nameEn: 'Music Note', category: '通用', aliasesZh: ['音符', '唱歌'] },
  { emojiId: 'default_question', nameEn: 'Question', category: '通用', aliasesZh: ['问号', '疑惑'] },
  { emojiId: 'default_stop', nameEn: 'Stop', category: '通用', aliasesZh: ['停', '停止'] },
  { emojiId: 'default_zzz', nameEn: 'Zzz', category: '通用', aliasesZh: ['睡觉', '困', '晚安'] },
];
